---
apiVersion: v1
kind: Template
metadata:
  name: dashdotdb
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: dashdotqueue
    name: dashdotqueue
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: dashdotqueue
    template:
      metadata:
        labels:
          app: dashdotqueue
      spec:
        containers:
        - image: quay.io/app-sre/rabbitmq
          imagePullPolicy: Always
          name: dashdotqueue
          ports:
          - name: dashdotqueue
            containerPort: 5672
- apiVersion: v1
  kind: Service
  metadata:
    name: dashdotqueue
    labels:
      app: dashdotqueue
  spec:
    ports:
      - protocol: TCP
        port: 5672
        targetPort: 5672
        name: dashdotqueue
    selector:
      app: dashdotqueue
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: dashdotsched
    name: dashdotsched
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: dashdotsched
    template:
      metadata:
        labels:
          app: dashdotsched
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: dashdotsched
          args: ["beat"]
          env:
            - name: DASHDOTDB_URL
              value: http://dashdotdb.dashdot.svc.cluster.local/api/v1
            - name: RABBITMQ_URL
              value: pyamqp://guest@dashdotqueue.dashdot.svc.cluster.local//
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${tokenSecret}
                  key: ACCESS_TOKEN
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: dashdotworker
    name: dashdotworker
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: dashdotworker
    template:
      metadata:
        labels:
          app: dashdotworker
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: dashdotworker
          args: ["worker"]
          env:
            - name: DASHDOTDB_URL
              value: http://dashdotdb.dashdot.svc.cluster.local/api/v1
            - name: RABBITMQ_URL
              value: pyamqp://guest@dashdotqueue.dashdot.svc.cluster.local//
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${tokenSecret}
                  key: ACCESS_TOKEN
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: dashdotflower
    name: dashdotflower
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: dashdotflower
    template:
      metadata:
        labels:
          app: dashdotflower
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: dashdotflower
          args: ["flower"]
          env:
            - name: DASHDOTDB_URL
              value: http://dashdotdb.dashdot.svc.cluster.local/api/v1
            - name: RABBITMQ_URL
              value: pyamqp://guest@dashdotqueue.dashdot.svc.cluster.local//
        - image: ${IMAGE_OAUTH2_PROXY}:${IMAGE_OAUTH2_PROXY_TAG}
          imagePullPolicy: Always
          name: dashdotflower-oauth2-proxy
          env:
          - name: OAUTH2_PROXY_PROVIDER
            valueFrom:
              secretKeyRef:
                name: ${oauth2ProxySecret}
                key: oauth2.proxy.provider
          - name: OAUTH2_PROXY_GITHUB_ORG
            valueFrom:
              secretKeyRef:
                name: ${oauth2ProxySecret}
                key: oauth2.proxy.github.org
          - name: OAUTH2_PROXY_REDIRECT_URL
            valueFrom:
              secretKeyRef:
                name: ${oauth2ProxySecret}
                key: oauth2.proxy.redirect.url
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: ${oauth2ProxySecret}
                key: oauth2.proxy.cookie.secret
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: ${oauth2ProxySecret}
                key: oauth2.proxy.client.id
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${oauth2ProxySecret}
                key: oauth2.proxy.client.secret
          args:
          - -http-address=0.0.0.0:4180
          - -email-domain=*
          - -upstream=http://localhost:5555
          - -cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
          - -client-id=$(OAUTH2_PROXY_CLIENT_ID)
          - -client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
          - -provider=$(OAUTH2_PROXY_PROVIDER)
          - -github-org=$(OAUTH2_PROXY_GITHUB_ORG)
          - -redirect-url=$(OAUTH2_PROXY_REDIRECT_URL)
- apiVersion: v1
  kind: Service
  metadata:
    name: oauth2-proxy
    labels:
      app: dashdotflower
  spec:
    type: ClusterIP
    ports:
      - name: https
        port: 443
        targetPort: 4180
        protocol: TCP
    selector:
      app: dashdotflower
parameters:
- name: IMAGE
  value: quay.io/app-sre/dashdotcollector
- name: IMAGE_TAG
  value: latest
- name: IMAGE_OAUTH2_PROXY
  value: quay.io/pusher/oauth2_proxy
- name: IMAGE_OAUTH2_PROXY_TAG
  value: v4.0.0-amd64
- name: tokenSecret
  value: access-token
- name: oauth2ProxySecret
  value: oauth2-proxy-stage
